### PR TITLE
Closes softlayer/sl-ember-behavior#103

### PR DESCRIPTION
**Pull request by juwara0**
This PR is for issue: https://github.com/softlayer/sl-ember-behavior/issues/103

Wrote integration tests for sl-able
Removed unit tests from sl-able
Added a mixin test to verify component.js is mixed in to sl-able

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-behavior/142)

### CODE REVIEW

**Comment by azizpunjani** [comment]
<sup>**[tests/integration/components/sl-able-test.js, line 82 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K10pP2lymE5bUU4sng8)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/2b9aa734e95af6b7113727493d7f0f218e120b4d/tests/integration/components/sl-able-test.js#L82)):</sup>
Since this template is exactly the same as the one above in this test block, it can probably be cached in a variable and used in both render calls, this will shorten the code a little and make the test slightly faster.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by juwara0** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 82 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K10pP2lymE5bUU4sng8)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/2b9aa734e95af6b7113727493d7f0f218e120b4d/tests/integration/components/sl-able-test.js#L82)):</sup>
Good idea. Thanks



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by notmessenger** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 108 [r2]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K14HyzccV44grHHDKNK)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/ef97ca00ee286743aa898aa114de49fd7b7fa6fd/tests/integration/components/sl-able-test.js#L108)):</sup>
Would it be more accurate to set possible to true, since there is an expectation that with this value to true it will render, except that with the activity to false it will never happen?  Perhaps even testing both true and false to verify that it has no impact, though unit test of the service/component should be taking care of that.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 108 [r2]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K14HyzccV44grHHDKNK)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/ef97ca00ee286743aa898aa114de49fd7b7fa6fd/tests/integration/components/sl-able-test.js#L108)):</sup>
The previous test covers the scenario when activity is true and possible is toggled between false and true. This test is just to verify that when activity is false that possible is ignored.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 108 [r2]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K14HyzccV44grHHDKNK)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/ef97ca00ee286743aa898aa114de49fd7b7fa6fd/tests/integration/components/sl-able-test.js#L108)):</sup>
I guess it's the statement in the assertion call then.  It does not reflect what is happening, as possible has no impact on yielded content in this scenario.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 108 [r2]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K14HyzccV44grHHDKNK)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/ef97ca00ee286743aa898aa114de49fd7b7fa6fd/tests/integration/components/sl-able-test.js#L108)):</sup>
I will update the assertion statement to better reflect what is happening



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by juwara0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-able-test.js, line 108 [r2]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142#-K14HyzccV44grHHDKNK)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/ef97ca00ee286743aa898aa114de49fd7b7fa6fd/tests/integration/components/sl-able-test.js#L108)):</sup>
Upon further examination, I have determined that this test is unnecessary since it is testing the scenario where activity is false and possible is true (the default). I already have a test where activity is false is tested and the possible equals true (the default) is picked used. It is the second test in this suite.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/142)

**Pull request merged**
