### PR TITLE
sl-unable integration test suite

### PR DESCRIPTION
**Pull request by juwara0**
Closes softlayer/sl-ember-behavior#104: https://github.com/softlayer/sl-ember-behavior/issues/104

Added integration tests for sl-unable
Added mixin test to sl-unable unit test suite
Removed one extra value not needed from the sl-able integration test setup

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-behavior/144)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Comment by notmessenger** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/integration/components/sl-unable-test.js, line 59 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144#-K15wV1lXA1jzq0FG692)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/1f108eb664701af05242c47b9fdf9790588fed1b/tests/integration/components/sl-unable-test.js#L59)):</sup>
s/effects/affects



---

<sup>**[tests/unit/components/sl-unable-test.js, line 40 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144#-K15vfTmKDSEUXb89UnW)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/1f108eb664701af05242c47b9fdf9790588fed1b/tests/unit/components/sl-unable-test.js#L40)):</sup>
Can/should this be removed?



---

<sup>**[tests/unit/components/sl-unable-test.js, line 54 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144#-K15vajTssTWmV3fJa8r)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/1f108eb664701af05242c47b9fdf9790588fed1b/tests/unit/components/sl-unable-test.js#L54)):</sup>
Can/should this be removed?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Comment by notmessenger** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Comment by juwara0** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[tests/unit/components/sl-unable-test.js, line 40 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144#-K15vfTmKDSEUXb89UnW)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/1f108eb664701af05242c47b9fdf9790588fed1b/tests/unit/components/sl-unable-test.js#L40)):</sup>
Done.



---

<sup>**[tests/unit/components/sl-unable-test.js, line 54 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144#-K15vajTssTWmV3fJa8r)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/1f108eb664701af05242c47b9fdf9790588fed1b/tests/unit/components/sl-unable-test.js#L54)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Comment by notmessenger** [comment]
Merge conflict



---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/144)

**Pull request merged**
