### PR TITLE
Issue126

### PR DESCRIPTION
**Pull request by notmessenger**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-behavior/136)

### CODE REVIEW

**Comment by azizpunjani** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/components/sl-able-test.js, line 36 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10bHNwFbxkspYY9iNL)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-able-test.js#L36)):</sup>
We should probably unregister this template at the end of this test block.



---

<sup>**[tests/unit/components/sl-able-test.js, line 56 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10aa4lYvV_bwZK8A42)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-able-test.js#L56)):</sup>
I believe we should always register a template and pass the `templateName` property to the subject with the template we registered. 

If you change `returns( false )` to `returns( true )` in the stub above, you will notice the test still passes, because the template is not rendered.



---

<sup>**[tests/unit/components/sl-unable-test.js, line 48 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10bZtEnDmPpYMjmJ6u)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-unable-test.js#L48)):</sup>
We should probably unregister this template at the end of this test block.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by azizpunjani** [comment]
<sup>**[tests/unit/components/sl-unable-test.js, line 37 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10ciR08XXhSAQ5kwJ3)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-unable-test.js#L37)):</sup>
I believe we should always register a template and pass the `templateName` to `this.subject(...`.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by azizpunjani** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[tests/unit/components/sl-able-test.js, line 36 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10bHNwFbxkspYY9iNL)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-able-test.js#L36)):</sup>
Agreed - and it's part of the style guide to do so :-/



---

<sup>**[tests/unit/components/sl-unable-test.js, line 48 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136#-K10bZtEnDmPpYMjmJ6u)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/4fea244e9c0a2e23d26d88cb0eeee831497dd2ad/tests/unit/components/sl-unable-test.js#L48)):</sup>
Agreed - and it's part of the style guide to do so :-/



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by notmessenger** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by juwara0** [comment]
I have reviewed this and it looks ok to merge.



---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Comment by juwara0** [comment]
It looks like some commit checks failed...



---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/136)

**Pull request closed without merging**
