### PR TITLE
Replace Ember.assert with Error/warn Closes #88

### LINKED ISSUE #88: Evaluate use of Ember.assert()
and replace with either `throw new Ember.Error()` or `warn` in addon/mixins/component.js

### PR DESCRIPTION
**Pull request by Yogeswar**
Closes #88 softlayer/sl-ember-behavior#88

[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-behavior/148)

### CODE REVIEW

**Comment by notmessenger** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/mixins/component.js, line 65 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3FdryAomMWFWbu0bBn)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L65)):</sup>
This is not the correct `@throws` value, however by making the changes listed below it then will.



---

<sup>**[addon/mixins/component.js, line 69 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3Fdj9l5-9AIJBOdJj9)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L69)):</sup>
Should be `Ember.Error()` rather than `warn()`.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148)

**Comment by Yogeswar** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/mixins/component.js, line 69 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3Fdj9l5-9AIJBOdJj9)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L69)):</sup>
using Ember.Error() makes the return statement below obsolete. I would have to remove that and the corresponding test case.

I figured that we still wanted to return a return value.  If not I'll update the function according.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148)

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/mixins/component.js, line 69 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3Fdj9l5-9AIJBOdJj9)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L69)):</sup>
As did the use of `Ember.assert()`, though it had the potential of being stripped out of the build depending on settings in the consuming application.  There is no good way (presently) to enforce abstract methods which is why this approach had to be implemented.  Throwing an error in our add ons should be used when the condition not being satisfied will cause functionality to break, and warnings should be thrown when functionality may only be compromised, perhaps visually or other, but will not affect logic workflows.

In this case, not overriding this method will cause logic problems, as it will always return false from this method, which obviously may not always be the desired output.  Once an object uses this mixin an defines their own `isViewable()` method, then this error will cease to be thrown, "cleaning" everything up.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148)

**Comment by Yogeswar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[addon/mixins/component.js, line 65 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3FdryAomMWFWbu0bBn)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L65)):</sup>
changed back to Ember.assert



---

<sup>**[addon/mixins/component.js, line 69 [r1]](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148#-K3Fdj9l5-9AIJBOdJj9)** ([raw file](https://github.com/softlayer/sl-ember-behavior/blob/09c22bd3fceb38d616647497577db7f7e06bcfc7/addon/mixins/component.js#L69)):</sup>
changed back to Ember.assert.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148)

**Comment by notmessenger** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-behavior/148)

**Pull request merged**
